Models/Contato.cs
namespace ContatoWeb.Models
{
    public class Contato
    {
        public int ContatoId { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public int GrupoId { get; set; }
    }
}

Models/Grupo.cs
using System.ComponentModel.DataAnnotations;

namespace ContatoWeb.Models
{
    public class Grupo
    {
        public int GrupoId { get; set; }

        [Required(ErrorMessage="Campo nome obrigatório")]
        public string Nome { get; set; }
    }
}

Controllers/GrupoController.cs
using Microsoft.AspNetCore.Mvc;
using ContatoWeb.Data;
using ContatoWeb.Models;

namespace ContatoWeb.Controllers
{
    public class GrupoController : Controller
    {
        public IActionResult Index()
        {
            // using(var data = new GrupoData())
            // {
            //     var lista = data.Read();            
            //     return View(lista); // model => Lista<Grupo>
            
            // } // Dispose()

            using(var data = new GrupoData())           
                return View(data.Read());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Grupo grupo)
        {
            if(!ModelState.IsValid)
                return View(grupo);

            using(var data = new GrupoData())
                data.Create(grupo);
                
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            using(var data = new GrupoData())
                return View(data.Read(id));
        }

        [HttpPost]
        public IActionResult Update(int id, Grupo grupo)
        {
            grupo.GrupoId = id;

            if(!ModelState.IsValid)
                return View(grupo);

            using(var data = new GrupoData())
                data.Update(grupo);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            using(var data = new GrupoData())
                data.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

Views/Grupo/Create.cshtml
@model Grupo

@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "Cadastro de Grupo";
}

<form asp-controller="Grupo" asp-action="Create" method="POST">

    <div class="form-group">
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome"></span>
    </div>

    <button class="btn btn-primary">Salvar</button>
</form>

Views/Grupo/Index.cshtml
@model List<Grupo>

@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "Lista de Grupos";
}

    <table>
        @foreach (var grupo in Model)
        {
           <tr>
                <td>@grupo.GrupoId</td>
                <td>@grupo.Nome</td>
                <td>
                    <a href="/Grupo/Update/@grupo.GrupoId">Editar</a>
                </td>
                <td>
                    <a href="/Grupo/Delete/@grupo.GrupoId">Apagar</a>
                </td>
            </tr> 
        } 
    </table>
    <a href="/Grupo/Create">Adicionar</a>

Views/Grupo/Update.cshtml
@model Grupo

@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.Title = "Edição do Grupo";
}

<form asp-controller="Grupo" asp-action="Update" method="POST">

    <div class="form-group">
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome"></span>
    </div>

    <button class="btn btn-primary">Salvar</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>